version: '3'
services:
  cassandra-seed-server:
    build: ./cassandra
    container_name: cassandra-seed
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-server
      - CASSANDRA_CLUSTER_NAME=bdshr
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - ./cassandra/seed-datadir:/var/lib/cassandra

  cassandra-follower-server:
    build: ./cassandra
    container_name: cassandra-follower
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-server
      - CASSANDRA_CLUSTER_NAME=bdshr
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - ./cassandra/follower-datadir:/var/lib/cassandra
    depends_on:
          - cassandra-seed-server

  hie-mysql:
    image: mysql:5.6
    restart: always
    container_name: hie-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql/dumps/:/docker-entrypoint-initdb.d/
      - ./mysql/mysql-datadir:/var/lib/mysql

  identity-server:
    build:
      context: ../identity-server/
    container_name: identity-server
    ports:
      - "8084:8084"

  healthid-server:
    build:
      context: ../HealthId-Service/
    container_name: healthid-server
    ports:
      - "8086:8086"
    depends_on:
        - cassandra-follower-server

  mci-server:
    build:
      context: ../MCI-Service/
    container_name: mci-server
    ports:
      - "8081:8081"
    depends_on:
        - cassandra-follower-server

  shr-server:
      build:
        context: ../FreeSHR/
      container_name: shr-server
      ports:
        - "8082:8082"
      depends_on:
        - cassandra-follower-server

  tr-server:
      build:
        context: ../Terminology-Server
      container_name: tr-server
      ports:
        - "9080:9080"
      depends_on:
        - hie-mysql
